### ISSUE TITLE
Make output pretty

### ISSUE THREAD

**Issue by SillySam** [SillySam/Socket_Server#2]
Make the console output actually look nice. Colors would be nice (might want to check out `colorama` library) and making clear, simple prints. 👍

**Comment by AdityaMisra** [comment]
Hey, Can I work on this issue? I've some unanswered questions as well.

**Comment by SillySam** [comment]
@AdityaMisra Sure, go for it!

**Comment by AdityaMisra** [comment]
@SillySam I just have to use `colorama` library to add colors to all the print statements, right?

**Comment by SillySam** [comment]
@AdityaMisra Just those that seem appropriate to be colorful. Try to make the colors purposeful :D

**Comment by SillySam** [comment]
@AdityaMisra Thank you so much, you went above and beyond and I really appreciate your efforts!
